### ISSUE TITLE
Lexer checklist

### ISSUE THREAD

**Issue by MichaelHatherly** [JuliaDocs/Highlights.jl#3]
A list of lexers for different languages/filetypes that would be useful to have. For the most part this list should be based on what other source code highlighters (Pygments, Rouge, etc.) have implemented.

- [x] Julia: mostly complete, but still needs tests.
- [ ] Python.
- [ ] C and C++.
- [ ] Scheme, Common Lisp, Clojure, etc.
- [ ] MATLAB.
- [ ] R.
- [ ] Bash, Shell scripts, etc.
- [ ] hundreds of others...

**Comment by tkf** [comment]
It would be nice to add LLVM IR and ASM here. See https://github.com/JuliaDebug/Cthulhu.jl/pull/44

**Comment by miguelraz** [comment]
I'm adding a bump for `tkf`'s request here and an additional petition for `ptx`, of which there is already a `Pygments` port in [GPUCompiler](https://github.com/JuliaGPU/GPUCompiler.jl/pull/275).

**Comment by MichaelHatherly** [comment]
> If someone is willing to handhold me with a `ptx` PR I'll get around to it.

Just ping me when you have any questions. I've not looked at the codebase in a while, but shouldn't be too hard to get reacquainted with it.

**Comment by Ellipse0934** [comment]
I was doing the PR on PTX highlighting for `GPUCompiler` but I suppose this is the natural place to implement first. I will file a PR shortly. The `pygments` source for highlighting ptx isn't great imo and a specific highlighter should do a better job. I'll file a PR shortly.
